### PR TITLE
fix: check node and remote peer deref #660

### LINKED ISSUE #660: panic: runtime error: invalid memory address or nil pointer dereference
**Masa-Oracle version:**

v0.8.8
**Environment, CPU architecture, OS, and Version:**

ubuntu 24.04
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**

INFO[0970] Node left: /ip4/73.145.161.44/udp/4001/quic-v1/p2p/16Uiu2HAm1CMmCtWbbfkNR5RR7JE4CenemsVpBrkQW1ZNGfZYN2TC/p2p/16Uiu2HAm1CMmCtWbbfkNR5RR7JE4CenemsVpBrkQW1ZNGfZYN2TC
INFO[0970] [+] Staked node joined: /ip4/73.145.161.44/udp/4001/quic-v1/p2p/16Uiu2HAm1CMmCtWbbfkNR5RR7JE4CenemsVpBrkQW1ZNGfZYN2TC
INFO[0970] Node left: /ip4/195.7.6.180/udp/4001/quic-v1/p2p/16Uiu2HAkxpykDBLuDE1JDYALvVm77Ty8VBXtgDTewainq9GFQSV1/p2p/16Uiu2HAkxpykDBLuDE1JDYALvVm77Ty8VBXtgDTewainq9GFQSV1
INFO[0970] [+] Staked node joined: /ip4/195.7.6.180/udp/4001/quic-v1/p2p/16Uiu2HAkxpykDBLuDE1JDYALvVm77Ty8VBXtgDTewainq9GFQSV1
INFO[0970] Node left: /ip4/84.21.171.168/udp/4001/quic-v1/p2p/16Uiu2HAm1cmCTocSvZQUjrdbTAW3sUxSMTNsPHWiAokcvwfHQCD3
INFO[0970] [+] Staked node joined: /ip4/84.21.171.168/udp/4001/quic-v1/p2p/16Uiu2HAm1cmCTocSvZQUjrdbTAW3sUxSMTNsPHWiAokcvwfHQCD3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x407e16]

goroutine 51017 [running]:
github.com/masa-finance/masa-oracle/pkg/pubsub.(*NodeEventTracker).Disconnected(0xc00001d3c0, {0x383bfa8, 0xc0001b2000}, {0x3835ca0, 0xc00409c360})
        /root/masa-oracle/pkg/pubsub/node_event_tracker.go:178 +0x132
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Conn).doClose.func1.1({0x38088a8?, 0xc00001d3c0?})
        /root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.36.3/p2p/net/swarm/swarm_conn.go:95 +0x37
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).notifyAll(0xc0001b2000, 0xc004d1efb8)
        /root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.36.3/p2p/net/swarm/swarm.go:765 +0x9b
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Conn).doClose.func1()
        /root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.36.3/p2p/net/swarm/swarm_conn.go:94 +0xa7
created by github.com/libp2p/go-libp2p/p2p/net/swarm.(*Conn).doClose in goroutine 26
        /root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.36.3/p2p/net/swarm/swarm_conn.go:88 +0x1c9
make: *** [Makefile:33: run] Error 2
**Additional context**

### PR DESCRIPTION
**Pull request by alvin-reyes**
**Description**

This PR fixes #660 

**Notes for Reviewers**

#### Test - Run without the changes

Pasted Graphic

#### Test - Run with the changes

```
INFO[0007] [+] Staked node joined:  /ip4/127.0.0.1/udp/4001/quic-v1 /ip4/208.85.23.229/udp/4001/quic-v1 
INFO[0008] Node left: /ip4/172.21.0.4/udp/4001/quic-v1/p2p/16Uiu2HAmAfa4Yat5fHYUioetzrijoeeeXa2UEmZSWxujFkTQXTeM/p2p/16Uiu2HAmAfa4Yat5fHYUioetzrijoeeeXa2UEmZSWxujFkTQXTeM 
INFO[0008] [+] Staked node joined: /ip4/172.21.0.4/udp/4001/quic-v1/p2p/16Uiu2HAmAfa4Yat5fHYUioetzrijoeeeXa2UEmZSWxujFkTQXTeM 
INFO[0008] [+] Disconnected                              Peer=16Uiu2HAmCX3hNfidefJKQtK3qk7ChcU8ctuLrXsdaN35zDXfM4uJ conn="<swarm.Conn[*libp2pquic.transport] /ip4/0.0.0.0/udp/4001/quic-v1 (16Uiu2HAm3dXEHYzFH21Z9vE5DfmytdsaY3jKtdNVmQVHwyKkqtMG) <-> /ip4/217.15.167.23/udp/4001/quic-v1 (16Uiu2HAmCX3hNfidefJKQtK3qk7ChcU8ctuLrXsdaN35zDXfM4uJ)>" network="<Swarm 16Uiu2HAm3dXEHYzFH21Z9vE5DfmytdsaY3jKtdNVmQVHwyKkqtMG>"
INFO[0008] [+] Connected                                 Peer=16Uiu2HAmU9W1TYtnV5cn6ex7r3QVXVP8NHN4fmG6KCpDGAuPphjE conn="<swarm.Conn[*libp2pquic.transport] /ip4/0.0.0.0/udp/4001/quic-v1 (16Uiu2HAm3dXEHYzFH21Z9vE5DfmytdsaY3jKtdNVmQVHwyKkqtMG) <-> /ip4/45.32.231.88/udp/4001/quic-v1 (16Uiu2HAmU9W1TYtnV5cn6ex7r3QVXVP8NHN4fmG6KCpDGAuPphjE)>" network="<Swarm 16Uiu2HAm3dXEHYzFH21Z9vE5DfmytdsaY3jKtdNVmQVHwyKkqtMG>"
INFO[0009] Node left: /ip4/46.4.80.43/udp/4001/quic-v1/p2p/16Uiu2HAmRiQjmo11qbdHNt8gVVVBzbA2oXpAu1mnF6mCPsaZ7ikx/p2p/16Uiu2HAmRiQjmo11qbdHNt8gVVVBzbA2oXpAu1mnF6mCPsaZ7ikx 
INFO[0009] [+] Staked node joined: /ip4/172.18.0.2/udp/4001/quic-v1/p2p/16Uiu2HAmRiQjmo11qbdHNt8gVVVBzbA2oXpAu1mnF6mCPsaZ7ikx 
INFO[0009] [+] Connected                                 Peer=16Uiu2HAmKVMoq4WMZGzJXHeVABFkuygKR
```

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

File: pkg/pubsub/node_data.go [hunk 1]
```diff
@@ -164,7 +164,7 @@ func (n *NodeData) Joined(nodeVersion string) {
 
 	logMessage := fmt.Sprintf("[+] %s node joined: %s", map[bool]string{true: "Staked", false: "Unstaked"}[n.IsStaked], n.MultiaddrsString)
 	if n.IsStaked {
-		logrus.Info(logMessage)
+		logrus.Debug(logMessage)
```
Comment (mcamou) [inline pkg/pubsub/node_data.go:167]: Why this change? I think it does make sense to leave it as `Info` for staked nodes. OTOH if we leave it as `Debug`, the `if` is pointless.

File: pkg/pubsub/node_data.go [hunk 2]
```diff
@@ -174,21 +174,25 @@ func (n *NodeData) Joined(nodeVersion string) {
...
+		n.LastLeftUnix = time.Now().Unix()
+		n.LastUpdatedUnix = n.LastLeftUnix
+		n.CurrentUptime = 0
+		n.Activity = ActivityLeft
+		n.IsActive = false
+
+		n.UpdateAccumulatedUptime()
+		logMessage := fmt.Sprintf("Node left: %s", address)
+		if n.IsStaked {
+			logrus.Debug(logMessage)
```
Comment (mcamou) [inline pkg/pubsub/node_data.go:192]: Same as above, why change `Info` to `Debug`? OTOH if we change it to `Debug` then the `if` is pointless.

File: pkg/pubsub/node_event_tracker.go [hunk 3]
```diff
@@ -135,30 +135,53 @@ func (net *NodeEventTracker) ListenClose(n network.Network, a ma.Multiaddr) {
...
-		if nodeData.IsActive {
-			// Node appears already connected, buffer this connect event
-			net.ConnectBuffer[peerID] = ConnectBufferEntry{NodeData: nodeData, ConnectTime: time.Now()}
-		} else {
-			nodeData.Joined(net.nodeVersion)
-			err := net.AddOrUpdateNodeData(nodeData, true)
-			if err != nil {
-				logrus.Error("[-] Error adding or updating node data: ", err)
-				return
+		if nodeData != nil {
```
Comment (mcamou) [inline pkg/pubsub/node_event_tracker.go:159]: In principle this should never happen thanks to the `if !exists` above (except if at some point we actually added a `nil` because of a bug).

**Review by mcamou — CHANGES_REQUESTED** [review]

**Review by mcamou — DISMISSED** [review]

File: pkg/pubsub/node_event_tracker.go [hunk 4]
```diff
@@ -155,10 +168,18 @@ func (net *NodeEventTracker) Connected(n network.Network, c network.Conn) {
 			}
 		}
 	}
+
```
Comment (restevens402) [inline pkg/pubsub/node_event_tracker.go:171]: This is surprising. Is there a situation where we have a panic to recover from? I'm interested about this block.

**Review by restevens402 — APPROVED** [review]
This is lovely! This has needed testing for some time. Thank you!
I am interested to talk about panic recovery and how you use them strategically.

File: pkg/pubsub/node_event_tracker.go (hunk 4 above)
Comment (mudler) [reply pkg/pubsub/node_event_tracker.go:171]: was about to ask the same - when I see recover in the code just raise red flags here that we panic or don't handle pointers correctly somewhere.

Comment (mcamou) [reply pkg/pubsub/node_event_tracker.go:171]: Now that I think about it, I'd already approved it, but needing `recover` here is a code smell. It might be warranted, but then I would appreciate an explanatory comment here.

**Review by mcamou — APPROVED** [review]
Looks really good! Thanks!

**Review by mcamou — APPROVED** [review]
Looks really good! Thanks!

File: pkg/pubsub/node_event_tracker.go (hunk 4 above)
Comment (mudler) [reply pkg/pubsub/node_event_tracker.go:171]: To be fair I'd avoid adding `recover` in our code because hides errors which are not correctly handled, but if you agree with it I'm fine. I'd second @mcamou here to leave a comment in the code at least on the reasoning if we are going to merge it.

Comment (mudler) [reply pkg/pubsub/node_event_tracker.go:171]: right, indeed my point is that by moving panics to logs makes them harder to surface until you analyze closely the logs, and run many instances of the binary. 

Making the application stop and yell the error out makes sure we catch these.
