### PR TITLE
fix: error handling in `MonitorWorkers`

### LINKED ISSUE #410: bug: panic nil in MonitorWorks function & refactor
Nil pointer sometimes kills the node on startup also code can be refactored to be more modular

## Logs
```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x101196390]

goroutine 947 [running]:
github.com/masa-finance/masa-oracle/pkg/workers.MonitorWorkers({0x101cbeed0, 0x1400034f360}, 0x1400014c700)
        /Users/brendanplayford/masa-oracle/pkg/workers/workers.go:392 +0x110
created by main.main in goroutine 1
        /Users/brendanplayford/masa-oracle/cmd/masa-node/main.go:100 +0x778
```

### PR DESCRIPTION
**Pull request by teslashibe**
Enhance Robustness of MonitorWorkers Function with Nil Checks & Refctor

This closes #410 

### Description

This PR introduces a series of enhancements to the `MonitorWorkers` function within the `workers.go` file, aimed at improving the robustness and reliability of the function. The primary focus of these changes is to prevent runtime errors caused by nil pointer dereferences, which were identified as a potential issue in the existing implementation as outlined in #410 . Additionally, the PR includes refactoring to improve code readability and maintainability without altering the core functionality of the function.

### Changes

1. **Nil Checks:** Added comprehensive nil checks at the beginning of the `MonitorWorkers` function to ensure that none of the critical components, `node.ActorRemote`, or `node.WorkerTracker.WorkerStatusCh` are nil before proceeding with the function's logic. This preemptive measure is designed to prevent the function from crashing due to nil pointer dereferences.

2. **Channel Close Checks:** Implemented checks for closed channels when receiving messages from `node.WorkerTracker.WorkerStatusCh` and `workerDoneCh`. These checks allow the function to exit gracefully in scenarios where the channels are closed unexpectedly, enhancing the function's error handling capabilities.

3. **Code Refactoring:**
    - Encapsulated the logic for processing validator data into a separate function named `processValidatorData`. This change improves the organization of the code and separates concerns for better readability.
    - Similarly, encapsulated the logic for processing work data into a function named `processWork`. This refactoring maintains the original logic while making the code structure more intuitive.

4. **Logging and Error Handling:** Maintained and slightly adjusted the logging of informational, debug, and error messages to reflect the changes in the function's structure. The adjustments ensure that error messages are clear and informative, especially in cases where the function's prerequisites are not met.

### CODE REVIEW

File: pkg/api/handlers_node.go [hunk 1]
```diff
@@ -376,50 +388,50 @@ func (api *API) ChatPageHandler() gin.HandlerFunc {
...
+			"IsWebScraper":     false,
+			"FirstJoined":      api.Node.FromUnixTime(time.Now().Unix()),
+			"LastJoined":       api.Node.FromUnixTime(time.Now().Unix()),
+			"CurrentUptime":    "0",
+			"TotalUptime":      "0",
+			"Rewards":          "Coming Soon!",
+			"BytesScraped":     "0 MB",
 		}
+
+		if api.Node != nil && api.Node.Host != nil {
```
Comment (mudler) [inline pkg/api/handlers_node.go:408]: same here - this isn't blocking, but again it's more _idiomatic_ and good practice in go to do things like (pseudocode ahead):

```
if badconditionhappening {
 return or bail out with an error message early
}
```

File: pkg/workers/workers.go [hunk 2]
```diff
@@ -408,52 +438,44 @@ func MonitorWorkers(ctx context.Context, node *masa.OracleNode) {
...
 		case <-ctx.Done():
 			return
 		}
 	}
 }
+
+func processValidatorData(data *pubsub2.Message, validatorDataMap map[string]interface{}, startTime *time.Time, node *masa.OracleNode) {
+	if response, ok := validatorDataMap["Response"].(map[string]interface{}); ok {
+		if _, ok := response["error"].(string); ok {
+			logrus.Infof("[+] Work failed %s", response["error"])
```
Comment (mudler) [inline pkg/workers/workers.go:451]: small nit: that might have been a good candidate for a switch

**Review by mudler — APPROVED** [review]
Looking good!
